# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup PNPM
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@935101478d12d633ea2e71bb8b63d18e00bda099
      uses: pnpm/action-setup@v1.2.0
      with:
        # Version of PNPM to install
        version: 5.18.1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - run: pnpm i -g @microsoft/rush
    - run: rush install
    - run: rush rebuild
#    - uses: GabrielBB/xvfb-action@v1.0
#      with:
#        run: rush unit-test
